"""
Django settings for djangoencuestas project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from datetime import timedelta

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5y(ewun!t1@ig#svsq*3l-r37csgkfu@ch^3z)m_vl1aoi-w^4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'registration',
    'corsheaders', #CORS
    'graphos',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nucleo',
    'qr',
    'qr_code',
    'encuestas',
    'rest_framework',
    'contactar',
    # 'push_notifications',
    'notificaciones_push',
    'estadisticas',
    'testing',
    
    
]

PUSH_NOTIFICATIONS_SETTINGS = {
        "FCM_API_KEY": "AAAABEslyvo:APA91bE7bqyLb7LEq7JAtUJqmZq_XOD05GriVJgLCP76AzFD-6JIU9FhOMyt3kVi-IYVpRf-a6tj84cZMcIBdXOCRAwFLPjXWhroagnl1pKmv4cRqKbj2kmGpXXlTczI_RIG0ccfLH0k",
        "GCM_API_KEY": "AAAABEslyvo:APA91bE7bqyLb7LEq7JAtUJqmZq_XOD05GriVJgLCP76AzFD-6JIU9FhOMyt3kVi-IYVpRf-a6tj84cZMcIBdXOCRAwFLPjXWhroagnl1pKmv4cRqKbj2kmGpXXlTczI_RIG0ccfLH0k"
        # "APNS_CERTIFICATE": "/path/to/your/certificate.pem",
        # "APNS_TOPIC": "com.example.push_test",
        # "WNS_PACKAGE_SECURITY_ID": "[your package security id, e.g: 'ms-app://e-3-4-6234...']",
        # "WNS_SECRET_KEY": "[your app secret key, e.g.: 'KDiejnLKDUWodsjmewuSZkk']",
        # "WP_PRIVATE_KEY": "/path/to/your/private.pem",
        # "WP_CLAIMS": {'sub': "mailto: development@example.com"}
}

REST_FRAMEWORK = {
    # Mira bien este temita 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.AllowAny'
    # # ]

    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated'
    # ),

    # 'DEFAULT_AUTHENTICATION_CLASSES': (
        
    #     'rest_framework_simplejwt.authentication.JWTAuthentication',
    # )
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME' : timedelta(minutes=3000),
    'REFRESH_TOKEN_LIFETIME' : timedelta(days=3),
}

CORS_ORIGIN_ALLOW_ALL = True #CORS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', #CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoencuestas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoencuestas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3test'),
    }
}



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'RAY',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': '127.0.0.1',
#         'PORT': '3306',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

#UBICACION FICHEROS ESTÁTICOS

STATIC_URL = '/static/'

# REDIRECCIONES APP REGISTRATION

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


#DATOS CONEXION EMAIL


EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'xiskillotesting@gmail.com'
EMAIL_HOST_PASSWORD = 'testingxiskillo'
EMAIL_PORT = '587'
EMAIL_USE_TLS = True