# Generated by Django 2.2.1 on 2019-05-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuestas',
            options={'ordering': ['-created'], 'verbose_name': 'Encuesta', 'verbose_name_plural': 'Encuestas'},
        ),
        migrations.AlterModelOptions(
            name='pacientes',
            options={'ordering': ['-created'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='procedimientos',
            options={'ordering': ['-created'], 'verbose_name': 'Procedimiento', 'verbose_name_plural': 'Procedimientos'},
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='pregunta',
            field=models.TextField(blank=True, null=True, verbose_name='Pregunta de la Encuesta'),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='respuesta',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta a la Pregunta'),
        ),
    ]
