# Generated by Django 2.2.1 on 2019-05-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0006_auto_20190525_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='nuhsa',
            field=models.CharField(max_length=20, verbose_name='NUHSA'),
        ),
    ]
